### ISSUE TITLE
Migrate to System.Text.Json

### ISSUE THREAD

**Issue by gregsdennis** [charlesdevandiere/graphql-query-builder-dotnet#14]
Would love to see this drop the Newtonsoft dependency.

**Comment by sharpSteff** [comment]
Great lib 
I would love to use it, but can not because of this dependency.

I need to inject a query formater for System.Text.Json
Unfortunately the QueryOptions only has a Func<string,string>.

With Func<PropertyInfo,string> it would be possible to pass a Formatter for the System.Text.Json-Lib

`
    public class QueryOptions
    {
        public Func<string, string> Formatter { get; set; }
`

**Comment by charlesdevandiere** [comment]
Hi,

The formatter is now `Func<PropertyInfo, string>` and I made 2 satellite libs [GraphQL.Query.Builder.Formatter.NewtonsoftJson](https://www.nuget.org/packages/GraphQL.Query.Builder.Formatter.NewtonsoftJson) and [GraphQL.Query.Builder.Formatter.SystemTextJson](https://www.nuget.org/packages/GraphQL.Query.Builder.Formatter.SystemTextJson)

GraphQL.Query.Builder no longer has any dependencies
